### ISSUE TITLE
Usuário

### ISSUE THREAD

**Issue by thiagolima86** [Coding-in-community/fingest#1]
Acredito que devemos inicar o nosso projeto pelo usuário e autenticação desse usuário.

# Inicialmente precisaremos de:

[ Ver o MER](../blob/main/doc/diagramas/cash_flow.md)

- Criar o CRUD
- Usar uma GEM para fazer autenticação (devise)

*NÂO esquecer de fazer TDD*

IMPORTANTE
Não trabalhe na Master. Crie uma branch e suba e depois faça um pull request. Não aprove seu proprio pull request

**Comment by Gabriel-Ayala** [comment]
@thiagolima86 vou fechar a issue por já estar sendo implementado essa demanda
