### ISSUE TITLE
Utilização de Views

### ISSUE THREAD

**Issue by krlosgilson** [Coding-in-community/fingest#11]
Já está definido que o FrontEnd será com React.

Mesmo assim, o Rails poderá ter suas views habilitadas ou apenas os Controllers e Models? Pois vi que tem no Trello uma tarefa para fazer o Controller Home que irá gerenciar a rota _index_ .

**Comment by thiagolima86** [comment]
Vamos usar o Rails com MVC. 9 react sera integrado as views.
