### ISSUE TITLE
Qual tecnologia usaremos no Frontend?

### ISSUE THREAD

**Issue by thiagolima86** [Coding-in-community/fingest#2]
Pessoal, de novo voltamos a tratar sobre o frontend,

Apesar de termos fechado com o nextjs, mas estamos encontrando nosso primeiro problema. Não encontramos pessoas interessadas em trabalhar com nextjs. Nossa equipe backend tem bastante gente, mas o front, ta dificil.

Quero reabrir a discusão.

**Comment by thiagolima86** [comment]
Na minha opnião, a gente voltaria com a ideia de trabalhar com as views no proprio rails. Por alguns motivos.

 - O rails já tem um sistema de engenharia de template integrado.
 - Todo mundo, até os backend conseguem ajudar,
 - não há necessidade de 2 servidores, duas instalações, isso facilita pro usuário que vai instalar (infra simples)
 - Dá pra instalar react e vuejs ( só não sei como faz com react)
 - Pessoas que sabem html e css podem ajudar
 - Unifica a equipe
 - Podemos Ajustar o scaffold para gerar com o frontend certo automaticamente
 - A gente fica mais focado em funcionalidade e menos em boniteza. :)

**Comment by Gabriel-Ayala** [comment]
Acredito que isso muda toda a estrutura inicial do Backend se passar a usarmos View e na escolha do React teremos que usar WebPacker mas tem gem para integrar o uso no Rails

**Comment by thiagolima86** [comment]
É verdade. Vamos ter que descobrir como adicionar a estrutura de view para usar o wevpacker

**Comment by Gabriel-Ayala** [comment]
@thiagolima86 vou fechar a Issue pois o @lcspaiva87 ja definiu que React vai faciltar o desenvolvimento do Front End
