### ISSUE TITLE
Sugestão para banco de dados

### ISSUE THREAD

**Issue by thiagolima86** [Coding-in-community/fingest#3]
## Opnião
Acho que poderiamos trabalhar em desenvolvimento com o _Sqlite3_ , Mas deiva instalada a gem do postgres para quem quiser trocar para postgres ficar fácil.

## Mas porque não fazer o contrário?
Se a gente trabalhar com o postgres e depois quiser trocar para sqlite, pode ser problematico, porque o postgres é muito mais complexo e tem mais recurso. podemos acabar errando a mão e usando recursos que não tem no sqlite. Mas o contrario acredito que seja mais sucesso. Porque o sqlite3 é bem mais simples então o postgres tem os mesmo recursos.

---
A Ideia é simplificar ao maximo a instalação. uma vez que sqlite trabalha com um arquivo dentro do proprio servidor. Assim evitamos instalação de um servidor de banco de dados e fazer conexoes complexas. até a infra fica mais simples. A pessoa que usar vai usar 1 servidor apenas, só o puma. é facil até de criar um programa para executar. Ai teremos um sistema enxuto e facilimo de instalar. A gente pode deixar coisas mais complexar para uma versão comercial. e ainda assim é facil trocar o banco. dá pra usar postgres, mysql. No final o usuário pode usar o que ele quiser. é só instalar o banco e rodar migration nesse banco. Mas como se trata de um sistema pessoal, muito mini, acho que o sqlite é suficiente.

o que vocês acham?

**Comment by krlosgilson** [comment]
Concordo @thiagolima86, o sqlite é suficiente para o desenvolvimento. A escolha de um banco mais complexo fica a cargo do desenvolvedor ao colocar o sistema em produção.
