### ISSUE TITLE
Precisamos  de Logotipo

### ISSUE THREAD

**Issue by thiagolima86** [Coding-in-community/fingest#4]
Necessitamos de um logotipo com urgência. 
A partir do logotipo é que vamos determinar o esquema de cores do layout.

**Comment by Gabriel-Ayala** [comment]
@thiagolima86  a Paleta de Cores vai continuar verde

**Comment by thiagolima86** [comment]
verde mesmo.

**Comment by krlosgilson** [comment]
O logotipo já foi definido? Não seria o mesmo do grupo do whatsapp?
