### ISSUE TITLE
Framework CSS

### ISSUE THREAD

**Issue by thiagolima86** [Coding-in-community/fingest#6]
Pessoal, Mais uma decisão para tomarmos. Tenhamos cuidado neste ponto.

Precisamos decidir qual o ou os frameworks css iremos utilizar. 

aqui tem uma lista com os mais populares:
https://x-team.com/blog/best-css-frameworks/

**Comment by thiagolima86** [comment]
Pontos que eu acredito que são importantes
- Tem que ser popular
- Fácil de aprender
- Que tenha um design moderno
- Que tenha um material design completo

**Comment by DanielSPereira** [comment]
Styled Components, é moderno, fácil de trabalhar e tem uma boa integração com bibliotecas "animations".
Aqui um link com uma breve descrição:
https://blog.logrocket.com/8-reasons-to-use-styled-components-cf3788f0bb4d/

**Comment by thiagolima86** [comment]
Fechado com **Style components**
